const selectItems = {
    zhcx: [{
        dictCode: 'xzqy',
        dictLabel: '行政区域',
        id: 'xzqydmSj'
    },
    {
        dictCode: 'jqdj',
        dictLabel: '警情等级',
        id: 'jqdj'
    }, {
        dictCode: 'jqlx',
        dictLabel: '警情类型',
        id: 'sjlbdm'
    }, {
        dictCode: 'fsdw',
        dictLabel: '发送单位',
        id: 'jqtbzh'
    }, {
        dictCode: 'cddw',
        dictLabel: '出动队伍',
        id: 'xfdwdm'
    }, {
        dictCode: 'zrqdd',
        dictLabel: '责任区大队',
        id: 'zrqdddm'
    }, {
        dictCode: 'zzdw',
        dictLabel: '主战队伍',
        id: 'zzdw'
    }, {
        dictCode: 'czxs',
        dictLabel: '参战形式',
        id: 'respondType'
    }, {
        dictCode: 'tb_dic_czqk',
        dictLabel: '处置情况',
        id: 'czqkdm'
    }, {
        dictCode: 'tb_dic_hzqk',
        dictLabel: '到场时火灾情况',
        id: 'dcshzqkdm'
    }, {
        dictCode: 'tb_dic_hyzgbm',
        dictLabel: '行业主管部门',
        id: 'hyzgbm'
    }, {
        dictCode: 'sfcygyxfsgs',
        dictLabel: '是否采用公用消防栓供水',
        id: 'useHydrant'
    }, {
        dictCode: 'tb_dic_ddzhzw',
        dictLabel: '带队指挥员职务',
        id: 'zhyzw'
    }, {
        dictCode: 'tb_dic_xczh',
        dictLabel: '全勤指挥部',
        id: 'qqzhbZhcddm'
    }, {
        dictCode: 'sfylddw',
        dictLabel: '是否有联动单位',
        id: 'isLddw'
    }, {
        dictCode: 'tb_dic_fx',
        dictLabel: '风向',
        id: 'fxdm'
    }, {
        dictCode: 'tb_dic_qh',
        dictLabel: '天气',
        id: 'weather'
    }, {
        dictCode: 'sfng',
        dictLabel: '是否内攻',
        id: 'insideAttack'
    }, {
        dictCode: 'cdsfyrysw',
        dictLabel: '是否有人员伤亡',
        id: 'isCzrysw'
    }, {
        dictCode: 'cdbgzt',
        dictLabel: '报告状态',
        id: 'shztArr'
    }, {
        dictCode: 'sfzzdc',
        dictLabel: '是否正在调查',
        id: 'sfzzdc'
    }, {
        dictCode: 'tb_dic_zqdj',
        dictLabel: '火灾等级',
        id: 'zqlbdm'
    }, {
        dictCode: 'sfqwhz',
        dictLabel: '是否轻微火灾',
        id: 'qwhz'
    }, {
        dictCode: 'qydm',
        dictLabel: '区域 ',
        id: 'qydm'
    }, {
        dictCode: 'jdjcqk',
        dictLabel: '监督检查情况',
        id: 'jdjcqk'
    }, {
        dictCode: 'sgqtdcbm',
        dictLabel: '事故调查牵头部门',
        id: 'sgqtdcbm'
    }, {
        dictCode: 'tb_dic_jjlx',
        dictLabel: '经济类型',
        id: 'jjlxdm'
    }, {
        dictCode: 'tb_dic_qhcslb',
        dictLabel: '起火场所类型',
        id: 'qhcslb'
    }, {
        dictCode: 'qhcsdm',
        dictLabel: '起火场所',
        id: 'qhcsms'
    }, {
        dictCode: 'sfssjyc',
        dictLabel: '是否属世界遗产',
        id: 'sfsjycdm'
    }, {
        dictCode: 'jzyt',
        dictLabel: '建筑使用用途',
        id: 'jzsyyt'
    }, {
        dictCode: 'tb_dic_jzlb',
        dictLabel: '建筑类别',
        id: 'jzlbdm'
    }, {
        dictCode: 'tb_dic_jzwnhdj',
        dictLabel: '建筑耐火等级',
        id: 'jznhdjdm'
    }, {
        dictCode: 'tb_dic_jzjg',
        dictLabel: '建筑结构',
        id: 'jzjgdm'
    }, {
        dictCode: 'hzsfmydljjz',
        dictLabel: '火灾是否蔓延到临近建筑',
        id: 'hzsfmydljjz'
    }, {
        dictCode: 'sffshr',
        dictLabel: '是否发生轰燃',
        id: 'sffshr'
    }, {
        dictCode: 'mcsfkq',
        dictLabel: '门窗是否开启',
        id: 'shjzmcsfkq'
    }, {
        dictCode: 'xfssqk',
        dictLabel: '自动报警系统',
        id: 'zdbjxtsfaz'
    }, {
        dictCode: 'zdmhxt',
        dictLabel: '自动灭火系统',
        id: 'zdmhxtsfaz'
    }, {
        dictCode: 'fpyxt',
        dictLabel: '防排烟系统',
        id: 'fpyxtsfaz'
    }, {
        dictCode: 'fhjl',
        dictLabel: '防火卷帘',
        id: 'fhjl'
    }, {
        dictCode: 'snxhsxt',
        dictLabel: '室内消火栓系统',
        id: 'snxhsxtsaz'
    }, {
        dictCode: 'tb_dic_fhty',
        dictLabel: '防火分区',
        id: 'fhfq'
    }, {
        dictCode: 'fhjj',
        dictLabel: '防火间距',
        id: 'fhjj'
    }, {
        dictCode: 'sstd',
        dictLabel: '疏散通道',
        id: 'sstd'
    }, {
        dictCode: 'yjck',
        dictLabel: '紧急出口',
        id: 'yjck'
    }, {
        dictCode: 'yjsszm',
        dictLabel: '应急疏散照明',
        id: 'yjsszm'
    }, {
        dictCode: 'sflw',
        dictLabel: '联网情况',
        id: 'sflw'
    }, {
        dictCode: 'sfbx',
        dictLabel: '是否保险',
        id: 'sfbx'
    }, {
        dictCode: 'sfdfhzsg',
        dictLabel: '是否单方火灾事故',
        id: 'sfdfhzsh'
    }, {
        dictCode: 'qhwfldm',
        dictLabel: '起火物',
        id: 'qhwfldm'
    }, {
        dictCode: 'hzyydm',
        dictLabel: '火灾原因',
        id: 'hzyydm'
    }, {
        dictCode: 'tb_dic_dcfs',
        dictLabel: '调查方式',
        id: 'dcfs'
    }, {
        dictCode: 'hzsfyrysw',
        dictLabel: '是否有人员伤亡',
        id: 'sfyrsw'
    }, {
        dictCode: 'sfla',
        dictLabel: '是否立案',
        id: 'sfla'
    }, {
        dictCode: 'sfxsfh',
        dictLabel: '是否刑事放火',
        id: 'sfxsfh'
    }, {
        dictCode: 'sfsaqscsg',
        dictLabel: '是否属安全生产事故',
        id: 'sfaqscsg'
    }/* , {
        dictCode: 'hook',
        dictLabel: '是否已挂接',
        id: 'hook'
    } */, {
        dictCode: 'HZYYFLDM',
        dictLabel: '火灾原因未填写',
        id: 'HZYYFLDM'
    }, {
        dictCode: 'hzbgzt',
        dictLabel: '报告状态',
        id: 'tbZqxxQueryVoshzt'
    }, {
        dictCode: 'tb_dic_hylb',
        dictLabel: '行业类别',
        id: 'hylbdm'
    }
    ],
    jqcx: [{
        dictCode: 'xzqy',
        dictLabel: '行政区域',
        id: 'xzqydmSj'
    }, {
        dictCode: 'jqlx',
        dictLabel: '警情类型',
        id: 'sjlbdm'
    }, {
        dictCode: 'fsdw',
        dictLabel: '发送单位',
        id: 'jqtbzh'
    }, {
        dictCode: 'cddw',
        dictLabel: '出动队伍',
        id: 'xfdwdm'
    }, {
        dictCode: 'zrqdd',
        dictLabel: '责任区大队',
        id: 'zrqdddm'
    }, {
        dictCode: 'zzdw',
        dictLabel: '主战队伍',
        id: 'zzdw'
    }, 
    {
        dictCode: 'jqTagIds',
        dictLabel: '警情标签',
        id: 'jqTagIds'
    }
    ],
    cdcx: [
        {
            dictCode: 'xzqy',
            dictLabel: '行政区域',
            id: 'xzqydmSj'
        }, {
            dictCode: 'jqlx',
            dictLabel: '警情类型',
            id: 'sjlbdm'
        }, {
            dictCode: 'fsdw',
            dictLabel: '发送单位',
            id: 'jqtbzh'
        }, {
            dictCode: 'cddw',
            dictLabel: '出动队伍',
            id: 'xfdwdm'
        }, {
            dictCode: 'zrqdd',
            dictLabel: '责任区大队',
            id: 'zrqdddm'
        }, {
            dictCode: 'zzdw',
            dictLabel: '主战队伍',
            id: 'zzdw'
        }, {
            dictCode: 'czxs',
            dictLabel: '参战形式',
            id: 'respondType'
        }, {
            dictCode: 'tb_dic_czqk',
            dictLabel: '处置情况',
            id: 'czqkdm'
        }, {
            dictCode: 'tb_dic_hzqk',
            dictLabel: '到场时火灾情况',
            id: 'dcshzqkdm'
        }, {
            dictCode: 'tb_dic_hyzgbm',
            dictLabel: '行业主管部门',
            id: 'hyzgbm'
        }, {
            dictCode: 'sfcygyxfsgs',
            dictLabel: '是否采用公用消防栓供水',
            id: 'useHydrant'
        }, {
            dictCode: 'tb_dic_ddzhzw',
            dictLabel: '带队指挥员职务',
            id: 'zhyzw'
        }, {
            dictCode: 'tb_dic_xczh',
            dictLabel: '全勤指挥部',
            id: 'qqzhbZhcddm'
        }, {
            dictCode: 'sfylddw',
            dictLabel: '是否有联动单位',
            id: 'isLddw'
        }, {
            dictCode: 'tb_dic_fx',
            dictLabel: '风向',
            id: 'fxdm'
        }, {
            dictCode: 'tb_dic_qh',
            dictLabel: '天气',
            id: 'weather'
        }, {
            dictCode: 'sfng',
            dictLabel: '是否内攻',
            id: 'insideAttack'
        }, {
            dictCode: 'cdsfyrysw',
            dictLabel: '是否有人员伤亡',
            id: 'isCzrysw'
        }, {
            dictCode: 'cdbgzt',
            dictLabel: '报告状态',
            id: 'shztArr'
        }, {
            dictCode: 'tb_dic_hylb',
            dictLabel: '行业类别',
            id: 'hylbdm'
        }
    ],
    hzcx: [{
        dictCode: 'xzqy',
        dictLabel: '行政区域',
        id: 'xzqydmSj'
    }, {
        dictCode: 'jqlx',
        dictLabel: '警情类型',
        id: 'sjlbdm'
    }, {
        dictCode: 'fsdw',
        dictLabel: '发送单位',
        id: 'jqtbzh'
    }, {
        dictCode: 'cddw',
        dictLabel: '出动队伍',
        id: 'xfdwdm'
    }, {
        dictCode: 'zrqdd',
        dictLabel: '责任区大队',
        id: 'zrqdddm'
    }, {
        dictCode: 'zzdw',
        dictLabel: '主战队伍',
        id: 'zzdw'
    }, {
        dictCode: 'sfzzdc',
        dictLabel: '是否正在调查',
        id: 'sfzzdc'
    }, {
        dictCode: 'tb_dic_zqdj',
        dictLabel: '火灾等级',
        id: 'zqlbdm'
    }, {
        dictCode: 'sfqwhz',
        dictLabel: '是否轻微火灾',
        id: 'qwhz'
    }, {
        dictCode: 'qydm',
        dictLabel: '区域 ',
        id: 'qydm'
    }, {
        dictCode: 'jdjcqk',
        dictLabel: '监督检查情况',
        id: 'jdjcqk'
    }, {
        dictCode: 'sgqtdcbm',
        dictLabel: '事故调查牵头部门',
        id: 'sgqtdcbm'
    }, {
        dictCode: 'tb_dic_jjlx',
        dictLabel: '经济类型',
        id: 'jjlxdm'
    }, {
        dictCode: 'tb_dic_qhcslb',
        dictLabel: '起火场所类型',
        id: 'qhcslb'
    }, {
        dictCode: 'qhcsdm',
        dictLabel: '起火场所',
        id: 'qhcsms'
    }, {
        dictCode: 'sfssjyc',
        dictLabel: '是否属世界遗产',
        id: 'sfsjycdm'
    }, {
        dictCode: 'jzyt',
        dictLabel: '建筑使用用途',
        id: 'jzsyyt'
    }, {
        dictCode: 'tb_dic_jzlb',
        dictLabel: '建筑类别',
        id: 'jzlbdm'
    }, {
        dictCode: 'tb_dic_jzwnhdj',
        dictLabel: '建筑耐火等级',
        id: 'jznhdjdm'
    }, {
        dictCode: 'tb_dic_jzjg',
        dictLabel: '建筑结构',
        id: 'jzjgdm'
    }, {
        dictCode: 'hzsfmydljjz',
        dictLabel: '火灾是否蔓延到临近建筑',
        id: 'hzsfmydljjz'
    }, {
        dictCode: 'sffshr',
        dictLabel: '是否发生轰燃',
        id: 'sffshr'
    }, {
        dictCode: 'mcsfkq',
        dictLabel: '门窗是否开启',
        id: 'shjzmcsfkq'
    }, {
        dictCode: 'xfssqk',
        dictLabel: '自动报警系统',
        id: 'zdbjxtsfaz'
    }, {
        dictCode: 'zdmhxt',
        dictLabel: '自动灭火系统',
        id: 'zdmhxtsfaz'
    }, {
        dictCode: 'fpyxt',
        dictLabel: '防排烟系统',
        id: 'fpyxtsfaz'
    }, {
        dictCode: 'fhjl',
        dictLabel: '防火卷帘',
        id: 'fhjl'
    }, {
        dictCode: 'snxhsxt',
        dictLabel: '室内消火栓系统',
        id: 'snxhsxtsaz'
    }, {
        dictCode: 'tb_dic_fhty',
        dictLabel: '防火分区',
        id: 'fhfq'
    }, {
        dictCode: 'fhjj',
        dictLabel: '防火间距',
        id: 'fhjj'
    }, {
        dictCode: 'sstd',
        dictLabel: '疏散通道',
        id: 'sstd'
    }, {
        dictCode: 'yjck',
        dictLabel: '紧急出口',
        id: 'yjck'
    }, {
        dictCode: 'yjsszm',
        dictLabel: '应急疏散照明',
        id: 'yjsszm'
    }, {
        dictCode: 'sflw',
        dictLabel: '联网情况',
        id: 'sflw'
    }, {
        dictCode: 'sfbx',
        dictLabel: '是否保险',
        id: 'sfbx'
    }, {
        dictCode: 'sfdfhzsg',
        dictLabel: '是否单方火灾事故',
        id: 'sfdfhzsh'
    }, {
        dictCode: 'qhwfldm',
        dictLabel: '起火物',
        id: 'qhwfldm'
    }, {
        dictCode: 'hzyydm',
        dictLabel: '火灾原因',
        id: 'hzyydm'
    }, {
        dictCode: 'tb_dic_dcfs',
        dictLabel: '调查方式',
        id: 'dcfs'
    }, {
        dictCode: 'hzsfyrysw',
        dictLabel: '是否有人员伤亡',
        id: 'sfyrsw'
    }, {
        dictCode: 'sfla',
        dictLabel: '是否立案',
        id: 'sfla'
    }, {
        dictCode: 'sfxsfh',
        dictLabel: '是否刑事放火',
        id: 'sfxsfh'
    }, {
        dictCode: 'sfsaqscsg',
        dictLabel: '是否属安全生产事故',
        id: 'sfaqscsg'
    }, {
        dictCode: 'HZYYFLDM',
        dictLabel: '火灾原因未填写',
        id: 'HZYYFLDM'
    }, {
        dictCode: 'hzbgzt',
        dictLabel: '报告状态',
        id: 'tbZqxxQueryVoshzt'
    }, {
        dictCode: 'tb_dic_hylb',
        dictLabel: '行业类别',
        id: 'hylbdm'
    }, 
    {
        dictCode: 'zqTagIds',
        dictLabel: '火灾标签',
        id: 'zqTagIds'
    }
    ]
};

const numberItems = {
    zhcx: [{
        dictCode: '1',
        dictLabel: '距离现场（公里）',
        id: 'jlxcjldm'
    }, {
        dictCode: '2',
        dictLabel: '现场人员被困',
        id: 'xcrybkqkdm'
    }, {
        dictCode: '3',
        dictLabel: '气温',
        id: 'qw'
    }, {
        dictCode: '4',
        dictLabel: '投入车辆数',
        id: 'carCount'
    }, {
        dictCode: '5',
        dictLabel: '投入人员数',
        id: 'trrys'
    }, {
        dictCode: '22',
        dictLabel: '投入车辆总数',
        id: 'allCarCount'
    }, {
        dictCode: '23',
        dictLabel: '投入人员总数',
        id: 'allTrrys'
    }, {
        dictCode: '6',
        dictLabel: '起火面积(平方米)',
        id: 'qhmj'
    }, {
        dictCode: '7',
        dictLabel: '受灾人数',
        id: 'szrs'
    }, {
        dictCode: '8',
        dictLabel: '过火面积(平方米)',
        id: 'ghmj'
    }, {
        dictCode: '9',
        dictLabel: '受灾户数',
        id: 'szhs'
    }/*, {
        dictCode: '11',
        dictLabel: '死亡人数',
        id: 'dead_num'
    } , {
        dictCode: '12',
        dictLabel: '直接经济损失(元)',
        id: 'zzjjss_all'
    } */, {
        dictCode: '13',
        dictLabel: '直接财产损失(元)',
        id: 'zjccss'
    }, {
        dictCode: '14',
        dictLabel: '火灾现场处置费用(元)',
        id: 'hzxcczfy'
    }, {
        dictCode: '15',
        dictLabel: '人身伤亡支出(元)',
        id: 'ryswzc'
    }, {
        dictCode: '16',
        dictLabel: '死亡队员数',
        id: 'SWDYS'
    }, {
        dictCode: '17',
        dictLabel: '受伤队员数',
        id: 'SSDYS'
    }, {
        dictCode: '18',
        dictLabel: '死人数',
        id: 'SIRS'
    }, {
        dictCode: '19',
        dictLabel: '伤人数',
        id: 'SHRS'
    }, {
        dictCode: '20',
        dictLabel: '死伤总数',
        id: 'SSZS'
    }, {
        dictCode: '21',
        dictLabel: '抢救财产价值（元）',
        id: 'QJCCJZ'
    }],
    jqcx: [],
    cdcx: [{
        dictCode: '1',
        dictLabel: '距离现场（公里）',
        id: 'jlxcjldm'
    }, {
        dictCode: '2',
        dictLabel: '现场人员被困',
        id: 'xcrybkqkdm'
    }, {
        dictCode: '3',
        dictLabel: '气温',
        id: 'qw'
    }, {
        dictCode: '4',
        dictLabel: '投入车辆数',
        id: 'carCount'
    }, {
        dictCode: '5',
        dictLabel: '投入人员数',
        id: 'trrys'
    }, {
        dictCode: '6',
        dictLabel: '是否超时出动',
        id: 'isTimeoutCd'
    }
    /*, {
        dictCode: '11',
        dictLabel: '死亡人数',
        id: 'dead_num'
    }*/, {
        dictCode: '16',
        dictLabel: '死亡队员数',
        id: 'SWDYS'
    }, {
        dictCode: '17',
        dictLabel: '受伤队员数',
        id: 'SSDYS'
    }, {
        dictCode: '21',
        dictLabel: '抢救财产价值（元）',
        id: 'QJCCJZ'
    },
      {
        dictCode: '22',
        dictLabel: '保护财产价值（元）',
        id: 'protectPropVal'
      }, {
        dictCode: '23',
        dictLabel: '抢救人员数',
        id: 'rescueNum'
    }, {
        dictCode: '24',
        dictLabel: '疏散人员数',
        id: 'ssrs'
    }],
    hzcx: [{
        dictCode: '1',
        dictLabel: '起火面积(平方米)',
        id: 'qhmj'
    }, {
        dictCode: '2',
        dictLabel: '受灾人数',
        id: 'szrs'
    }, {
        dictCode: '8',
        dictLabel: '过火面积(平方米)',
        id: 'ghmj'
    }, {
        dictCode: '9',
        dictLabel: '受灾户数',
        id: 'szhs'
    }, {
        dictCode: '12',
        dictLabel: '直接经济损失(元)',
        id: 'zzjjss_all'
    }, {
        dictCode: '13',
        dictLabel: '直接财产损失(元)',
        id: 'zjccss'
    }, {
        dictCode: '14',
        dictLabel: '火灾现场处置费用(元)',
        id: 'hzxcczfy'
    }, {
        dictCode: '15',
        dictLabel: '人身伤亡支出(元)',
        id: 'ryswzc'
    }, {
        dictCode: '18',
        dictLabel: '死人数',
        id: 'SIRS'
    }, {
        dictCode: '19',
        dictLabel: '伤人数',
        id: 'SHRS'
    }, {
        dictCode: '20',
        dictLabel: '死伤总数',
        id: 'SSZS'
    }, {
        dictCode: '21',
        dictLabel: '轻伤人数',
        id: 'QSRS'
    }, {
        dictCode: '22',
        dictLabel: '重伤人数',
        id: 'ZSRS'
    }, {
        dictCode: '23',
        dictLabel: '是否火灾超时出动',
        id: 'isTimeoutZq'
    }]
};

const stringItems = {
    zhcx: [{
        dictCode: '1',
        dictLabel: '警情编码',
        id: 'jqbh'
    }, {
        dictCode: '2',
        dictLabel: '警情地址',
        id: 'jqfsdd'
    }, {
        dictCode: '3',
        dictLabel: '单位名称/户主名',
        id: 'hzm'
    }, {
        dictCode: '4',
        dictLabel: '119案件编号',
        id: 'caseNbr'
    }, {
        dictCode: '5',
        dictLabel: '带队指挥员姓名',
        id: 'zhy'
    }, {
        dictCode: '6',
        dictLabel: '风力',
        id: 'windForce'
    }, {
        dictCode: '7',
        dictLabel: '火灾技战术措施',
        id: 'hzJzscsdm'
    }, {
        dictCode: '8',
        dictLabel: '抢险救援战术措施',
        id: 'qxjyJzscsdm'
    }, {
        dictCode: '9',
        dictLabel: '微型消防站名称',
        id: 'wxxfzMc'
    }, {
        dictCode: '10',
        dictLabel: '民间救援队',
        id: 'mjjydMc'
    }, {
        dictCode: '11',
        dictLabel: '企业专职队名称',
        id: 'qyzzdMc'
    }, {
        dictCode: '12',
        dictLabel: '起火地点',
        id: 'zqdd'
    }, {
        dictCode: '13',
        dictLabel: '失火单位/户主联系电话',
        id: 'lxdh'
    }, {
        dictCode: '14',
        dictLabel: '单位统一社会信用代码',
        id: 'dwtyshxydm'
    }, {
        dictCode: '15',
        dictLabel: '所属行业',
        id: 'hylbdm'
    }
    ],
    jqcx: [{
        dictCode: '1',
        dictLabel: '警情编码',
        id: 'jqbh'
    }, {
        dictCode: '2',
        dictLabel: '警情地址',
        id: 'jqfsdd'
    }, {
        dictCode: '3',
        dictLabel: '单位名称/户主名',
        id: 'hzm'
    }, {
        dictCode: '4',
        dictLabel: '119案件编号',
        id: 'caseNbr'
    }],
    cdcx: [{
        dictCode: '1',
        dictLabel: '警情编码',
        id: 'jqbh'
    }, {
        dictCode: '2',
        dictLabel: '警情地址',
        id: 'jqfsdd'
    }, {
        dictCode: '3',
        dictLabel: '单位名称/户主名',
        id: 'hzm'
    }, {
        dictCode: '4',
        dictLabel: '119案件编号',
        id: 'caseNbr'
    }, {
        dictCode: '5',
        dictLabel: '带队指挥员姓名',
        id: 'zhy'
    }, {
        dictCode: '6',
        dictLabel: '风力',
        id: 'windForce'
    }, {
        dictCode: '7',
        dictLabel: '火灾技战术措施',
        id: 'hzJzscsdm'
    }, {
        dictCode: '8',
        dictLabel: '抢险救援战术措施',
        id: 'qxjyJzscsdm'
    }, {
        dictCode: '9',
        dictLabel: '微型消防站名称',
        id: 'wxxfzMc'
    }, {
        dictCode: '10',
        dictLabel: '民间救援队',
        id: 'mjjydMc'
    }, {
        dictCode: '11',
        dictLabel: '企业专职队名称',
        id: 'qyzzdMc'
    }
    ],
    hzcx: [{
        dictCode: '1',
        dictLabel: '警情编码',
        id: 'jqbh'
    }, {
        dictCode: '2',
        dictLabel: '警情地址',
        id: 'jqfsdd'
    }, {
        dictCode: '3',
        dictLabel: '单位名称/户主名',
        id: 'hzm'
    }, {
        dictCode: '4',
        dictLabel: '119案件编号',
        id: 'caseNbr'
    }, {
        dictCode: '5',
        dictLabel: '起火地点',
        id: 'zqdd'
    }, {
        dictCode: '6',
        dictLabel: '失火单位/户主联系电话',
        id: 'lxdh'
    }, {
        dictCode: '7',
        dictLabel: '单位统一社会信用代码',
        id: 'dwtyshxydm'
    }, {
        dictCode: '8',
        dictLabel: '所属行业',
        id: 'hylbdm'
    }
    ]
};

const dateItems = {
    zhcx: [{
        dictCode: '1',
        dictLabel: '接警起止时间',
        id: 'jjsj'
    }, {
        dictCode: '2',
        dictLabel: '起火时间',
        id: 'zqsj'
    }],
    jqcx: [{
        dictCode: '1',
        dictLabel: '接警起止时间',
        id: 'jjsj'
    }],
    cdcx: [{
        dictCode: '1',
        dictLabel: '接警起止时间',
        id: 'jjsj'
    }],
    hzcx: [{
        dictCode: '1',
        dictLabel: '接警起止时间',
        id: 'jjsj'
    }, {
        dictCode: '2',
        dictLabel: '起火时间',
        id: 'zqsj'
    }]
};

const relateSelectItems = {
    czxs: [{
        dictValue: '010000',
        dictLabel: '主战'
    }, {
        dictValue: '020000',
        dictLabel: '增援'
    }],
    sfcygyxfsgs: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfylddw: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfng: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    cdsfyrysw: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    cdbgzt: [{
        dictValue: '-3',
        dictLabel: '待完善'
    }, {
        dictValue: '-2',
        dictLabel: '被退回'
    }, {
        dictValue: '-1',
        dictLabel: '待修改'
    }, {
        dictValue: '0',
        dictLabel: '未送审'
    }, {
        dictValue: '1',
        dictLabel: '审核中'
    }, {
        dictValue: '2',
        dictLabel: '已审核'
    }, {
        dictValue: '3',
        dictLabel: '被挂起'
    }, {
        dictValue: '99',
        dictLabel: '已归档'
    }, {
        dictValue: '4',
        dictLabel: '被驳回'
    }],
    sfzzdc: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfqwhz: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfssjyc: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    hzsfmydljjz: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sffshr: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    mcsfkq: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfbx: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfdfhzsg: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    hzsfyrysw: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfla: [{
        dictValue: '0',
        dictLabel: '是'
    }, {
        dictValue: '1',
        dictLabel: '否'
    }],
    sfxsfh: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    sfsaqscsg: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }],
    hzbgzt: [{
        dictValue: '2',
        dictLabel: '已审核'
    }, {
        dictValue: '1',
        dictLabel: '审核中'
    }, {
        dictValue: '-1',
        dictLabel: '被终止'
    }, {
        dictValue: '-2',
        dictLabel: '被退回'
    }, {
        dictValue: '-3',
        dictLabel: '待完善'
    }],
    sflw: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '2',
        dictLabel: '否'
    }]/* ,
    hook: [{
        dictValue: '1',
        dictLabel: '是'
    }, {
        dictValue: '0',
        dictLabel: '否'
    }] */,
    HZYYFLDM: [{
        dictValue: '0',
        dictLabel: '是'
    }, {
        dictValue: '1',
        dictLabel: '否'
    }]
};


export {
    selectItems,
    numberItems,
    stringItems,
    dateItems,
    relateSelectItems
}
